version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: localhost #use pg-postgres if pgadmin is running on Same DOcker Environment else use Localhost
    environment:
      POSTGRES_USER: diamond_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: diamond_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis-diamond
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
